# ruff: noqa: E501
"""Bundled, dependency-free Agent Preset configuration console."""

PRESETS_DASHBOARD_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Preset 路由台</title>
<style>
:root{--ink:#14213a;--muted:#69758a;--paper:#f2f5fa;--panel:#fff;--nav:#14243a;--blue:#2d63d8;--blue-soft:#e8efff;--cyan:#238798;--cyan-soft:#e4f4f5;--green:#147a58;--green-soft:#e4f4ed;--amber:#a56712;--amber-soft:#fff1d8;--red:#bd3c49;--red-soft:#fbe9eb;--line:#d8dfeb;--line-soft:#e9edf3;--shadow:0 16px 48px rgba(20,33,58,.08)}
*{box-sizing:border-box}html{background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif}button,input,select,textarea{font:inherit;color:inherit}button,a,input,select,textarea,summary{outline-offset:3px}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid var(--blue)}
.signal-line{display:grid;grid-template-columns:22% 39% 39%;height:4px}.signal-line i:nth-child(1){background:var(--nav)}.signal-line i:nth-child(2){background:var(--blue)}.signal-line i:nth-child(3){background:var(--cyan)}
.page{width:min(1440px,calc(100% - 48px));margin:0 auto;padding:32px 0 52px}.masthead{display:flex;justify-content:space-between;gap:26px;align-items:flex-start;margin-bottom:22px}.identity{display:flex;gap:15px;align-items:flex-start}.mark{width:46px;height:46px;display:grid;place-items:center;border:1px solid #b9c6d8;border-radius:10px;background:#fff;color:var(--nav);font:800 12px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.05em;box-shadow:0 6px 18px rgba(20,36,58,.06)}.eyebrow{margin:0 0 5px;color:var(--blue);font:750 10px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.15em;text-transform:uppercase}h1{margin:0;font:760 30px/1.12 ui-rounded,"Arial Rounded MT Bold","PingFang SC",sans-serif;letter-spacing:-.035em}.intro{margin:7px 0 0;color:var(--muted)}.mast-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap;justify-content:flex-end}.text-link{color:var(--muted);font-weight:650;text-decoration:none;padding:8px 7px}.text-link:hover{color:var(--blue)}
.primary,.quiet,.danger,.icon-button{min-height:39px;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer}.primary{border:1px solid var(--blue);background:var(--blue);color:#fff}.primary:hover{background:#2455bb}.quiet,.icon-button{border:1px solid var(--line);background:#fff;color:var(--ink)}.quiet:hover,.icon-button:hover{border-color:#adb9ca;background:#f9fbfd}.danger{border:1px solid #e8bec3;background:#fff;color:var(--red)}.danger:hover{background:var(--red-soft)}button[disabled]{cursor:not-allowed;opacity:.58}
.route-board{display:grid;grid-template-columns:minmax(150px,1fr) 56px minmax(240px,1.35fr) 56px minmax(170px,1fr);align-items:center;padding:16px 18px;margin-bottom:20px;border:1px solid #cdd7e6;border-radius:11px;background:#edf2f8;box-shadow:inset 0 1px #fff}.route-node{display:flex;align-items:center;gap:11px;min-width:0}.route-node i{width:12px;height:12px;flex:0 0 12px;border:3px solid var(--blue);border-radius:50%;background:#fff;box-shadow:0 0 0 4px var(--blue-soft)}.route-node:last-child i{border-color:var(--cyan);box-shadow:0 0 0 4px var(--cyan-soft)}.route-node strong{display:block;font-size:12px}.route-node span{display:block;color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.route-wire{height:2px;background:#b7c5d8;position:relative}.route-wire:after{content:"";position:absolute;right:-1px;top:-3px;border-left:6px solid #8da1ba;border-top:4px solid transparent;border-bottom:4px solid transparent}
.workbench{display:grid;grid-template-columns:252px minmax(0,1fr);gap:18px;align-items:start}.filter-panel{position:sticky;top:18px;border:1px solid var(--line);border-radius:11px;background:#fff;overflow:hidden;box-shadow:0 8px 28px rgba(20,33,58,.05)}.filter-head{padding:15px 16px;border-bottom:1px solid var(--line-soft);background:#fbfcfe}.filter-head strong{display:block}.filter-head span{color:var(--muted);font-size:11px}.filters{display:grid;gap:13px;padding:16px}.field{display:grid;gap:6px}.field label,.field-label{color:var(--muted);font-size:11px;font-weight:750;letter-spacing:.035em}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line);border-radius:7px;background:#fff;padding:8px 10px}.field input,.field select{height:39px}.field textarea{min-height:82px;resize:vertical}.field input:hover,.field select:hover,.field textarea:hover{border-color:#aeb9c9}.filter-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.scope-note{padding:14px 16px;border-top:1px solid var(--line-soft);background:#fbfcfe;color:var(--muted);font-size:11px}.scope-note b{color:var(--ink)}
.registry{min-width:0}.registry-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:11px}.registry-head p{margin:0;color:var(--muted);font-size:12px}.registry-head strong{color:var(--ink);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.cards{display:grid;gap:11px}.preset-card{display:grid;grid-template-columns:minmax(230px,1.05fr) minmax(360px,1.6fr) auto;gap:18px;align-items:center;padding:17px 18px;border:1px solid var(--line);border-radius:11px;background:#fff;box-shadow:0 5px 18px rgba(20,33,58,.035);transition:border-color .16s ease,transform .16s ease,box-shadow .16s ease}.preset-card:hover{border-color:#b6c3d5;transform:translateY(-1px);box-shadow:0 10px 28px rgba(20,33,58,.065)}.preset-card.disabled{background:#f8f9fb;color:#69758a}.preset-title{display:flex;align-items:center;gap:8px;margin-bottom:7px}.preset-title h2{margin:0;min-width:0;overflow:hidden;text-overflow:ellipsis;font:750 17px/1.3 ui-rounded,"Arial Rounded MT Bold","PingFang SC",sans-serif}.revision{padding:2px 6px;border-radius:5px;background:#eef2f7;color:#59667a;font:700 10px ui-monospace,SFMono-Regular,Menlo,monospace}.description{margin:0 0 9px;color:var(--muted);font-size:12px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.badges,.skills,.limits{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.badge,.skill,.limit{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:3px 8px;font:700 10px ui-monospace,SFMono-Regular,Menlo,monospace}.badge.global{background:var(--blue-soft);color:#2858ba}.badge.repository{background:var(--cyan-soft);color:#1e7180}.badge.review{background:#edf0f5;color:#4c5a70}.badge.agent_task{background:var(--amber-soft);color:var(--amber)}.badge.enabled{background:var(--green-soft);color:var(--green)}.badge.off{background:#edf0f4;color:#6d7788}
.mini-route{display:grid;grid-template-columns:minmax(105px,.8fr) 25px minmax(145px,1fr) 25px minmax(105px,.8fr);align-items:center;margin-bottom:11px}.mini-node{min-width:0}.mini-node small{display:block;color:#8994a5;font:700 9px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em}.mini-node strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:700 12px ui-monospace,SFMono-Regular,Menlo,monospace}.arrow{height:1px;background:#c5cfdd;position:relative;margin:0 7px}.arrow:after{content:"";position:absolute;right:0;top:-3px;border-left:5px solid #98a9bf;border-top:3px solid transparent;border-bottom:3px solid transparent}.skill{background:#f1f4f8;color:#46556b}.skill.support{background:#eef7f8;color:#287382}.limit{padding-left:0;color:#68758a;font-weight:650}.limit b{color:var(--ink)}.card-actions{display:grid;gap:7px;min-width:94px}.card-actions button{width:100%}.empty,.loading,.load-error{display:grid;place-items:center;min-height:330px;padding:38px;border:1px dashed #c5cfdd;border-radius:11px;background:#f8fafc;text-align:center;color:var(--muted)}.empty strong,.load-error strong{display:block;color:var(--ink);font-size:16px}.empty p,.load-error p{max-width:420px;margin:6px 0 0}.load-error{border-color:#e6bdc2;background:#fff8f8}.load-error strong{color:var(--red)}
dialog{width:min(900px,calc(100vw - 32px));max-height:calc(100vh - 32px);padding:0;border:0;border-radius:13px;background:#fff;color:var(--ink);box-shadow:0 28px 90px rgba(9,22,42,.35)}dialog::backdrop{background:rgba(12,26,48,.68);backdrop-filter:blur(2px)}.editor{display:grid;grid-template-rows:auto minmax(0,1fr) auto;max-height:calc(100vh - 32px)}.editor-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding:20px 22px;border-bottom:1px solid var(--line);background:#f8fafc}.editor-head .eyebrow{margin-bottom:4px}.editor-head h2{margin:0;font:760 22px/1.2 ui-rounded,"Arial Rounded MT Bold","PingFang SC",sans-serif}.close{width:36px;height:36px;border:1px solid var(--line);border-radius:8px;background:#fff;cursor:pointer;font-size:20px}.editor-body{overflow:auto;padding:20px 22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-grid .wide{grid-column:1/-1}fieldset{margin:0 0 18px;padding:16px;border:1px solid var(--line);border-radius:10px}legend{padding:0 7px;color:var(--blue);font:750 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.11em;text-transform:uppercase}.hint{margin:5px 0 0;color:var(--muted);font-size:11px}.check-row{display:flex;align-items:center;gap:9px;min-height:39px}.check-row input{width:17px;height:17px;accent-color:var(--blue)}.repository-fields[hidden],.tool-fields[hidden]{display:none}.editor-foot{display:flex;justify-content:space-between;gap:12px;padding:14px 22px;border-top:1px solid var(--line);background:#fbfcfe}.editor-foot>div{display:flex;gap:8px}.json-preview{margin-top:4px}.json-preview summary{cursor:pointer;color:var(--muted);font-weight:700}.json-preview pre{max-height:260px;overflow:auto;padding:12px;border-radius:7px;background:#101d31;color:#dce8f5;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word}.form-error{display:none;margin:0 0 16px;padding:10px 12px;border:1px solid #edc4c9;border-radius:8px;background:var(--red-soft);color:var(--red);font-weight:650}.form-error.show{display:block}.toast{position:fixed;right:24px;bottom:24px;z-index:10;max-width:min(420px,calc(100vw - 48px));padding:11px 14px;border-radius:8px;background:var(--nav);color:#fff;box-shadow:0 12px 32px rgba(9,22,42,.28);opacity:0;transform:translateY(8px);pointer-events:none;transition:.18s ease}.toast.show{opacity:1;transform:none}.visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
@media(max-width:1020px){.preset-card{grid-template-columns:1fr}.card-actions{display:flex}.card-actions button{width:auto}.workbench{grid-template-columns:220px minmax(0,1fr)}}@media(max-width:760px){.page{width:min(100% - 28px,1440px);padding-top:22px}.masthead{display:grid}.mast-actions{justify-content:flex-start}.route-board{grid-template-columns:1fr;gap:11px}.route-wire{width:2px;height:26px;margin-left:5px}.route-wire:after{right:-3px;top:auto;bottom:0;border-top:6px solid #8da1ba;border-left:4px solid transparent;border-right:4px solid transparent;border-bottom:0}.workbench{grid-template-columns:1fr}.filter-panel{position:static}.filters{grid-template-columns:1fr 1fr}.filter-actions{grid-column:1/-1}.scope-note{display:none}.mini-route{grid-template-columns:1fr}.mini-route .arrow{width:1px;height:16px;margin:4px 0 4px 5px}.mini-route .arrow:after{right:-3px;top:auto;bottom:0;border-top:5px solid #98a9bf;border-left:3px solid transparent;border-right:3px solid transparent;border-bottom:0}.form-grid{grid-template-columns:1fr}.form-grid .wide{grid-column:auto}.editor-foot{align-items:center}.editor-foot>div{flex-wrap:wrap;justify-content:flex-end}}@media(max-width:480px){.filters{grid-template-columns:1fr}.filter-actions{grid-column:auto}.preset-card{padding:15px}.editor-head,.editor-body,.editor-foot{padding-left:15px;padding-right:15px}.editor-foot{display:grid}.editor-foot>div{justify-content:stretch}.editor-foot button{flex:1}.toast{right:14px;bottom:14px;max-width:calc(100vw - 28px)}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style>
</head>
<body>
<div class="signal-line" aria-hidden="true"><i></i><i></i><i></i></div>
<main class="page">
  <header class="masthead">
    <div class="identity"><div class="mark" aria-hidden="true">CFG</div><div><p class="eyebrow">Review orchestrator / configuration</p><h1>Agent Preset 路由台</h1><p class="intro">查看作用域如何组合 Agent、Skill、模型与执行预算，并在同一处安全修改。</p></div></div>
    <div class="mast-actions"><a class="text-link" data-token-link href="/dashboard/">运维总览</a><a class="text-link" data-token-link href="/reviews/">Review 台账</a><button class="primary" id="create" type="button">＋ 新建 Preset</button></div>
  </header>

  <section class="route-board" aria-label="Preset 解析顺序">
    <div class="route-node"><i></i><div><strong>匹配作用域</strong><span>Repository 优先于 Global</span></div></div><div class="route-wire" aria-hidden="true"></div>
    <div class="route-node"><i></i><div><strong>组合执行配置</strong><span>Agent · Task Type · Skills · Model · Limits</span></div></div><div class="route-wire" aria-hidden="true"></div>
    <div class="route-node"><i></i><div><strong>Runtime 二次校验</strong><span>Policy · Tool allow-list · Snapshot</span></div></div>
  </section>

  <div class="workbench">
    <aside class="filter-panel">
      <div class="filter-head"><strong>定位配置</strong><span>按匹配条件缩小路由表</span></div>
      <form class="filters" id="filters">
        <div class="field"><label for="filter-kind">任务类型</label><select id="filter-kind"><option value="">全部任务</option><option value="review">Review</option><option value="agent_task">AgentTask</option></select></div>
        <div class="field"><label for="filter-scope">作用域</label><select id="filter-scope"><option value="">全部作用域</option><option value="global">Global</option><option value="repository">Repository</option></select></div>
        <div class="field"><label for="filter-provider">代码平台</label><select id="filter-provider"><option value="">全部平台</option><option value="github">GitHub</option><option value="gitlab">GitLab</option></select></div>
        <div class="field"><label for="filter-repository">仓库</label><input id="filter-repository" maxlength="512" placeholder="owner/repository" autocomplete="off"></div>
        <div class="field"><label for="filter-enabled">状态</label><select id="filter-enabled"><option value="">全部状态</option><option value="true">已启用</option><option value="false">已停用</option></select></div>
        <div class="filter-actions"><button class="primary" type="submit">应用</button><button class="quiet" id="reset" type="button">重置</button></div>
      </form>
      <div class="scope-note"><b>解析规则</b><br>同一任务先匹配仓库配置，再回退全局配置；停用的资源不参与匹配。</div>
    </aside>

    <section class="registry" aria-labelledby="registry-title">
      <div class="registry-head"><p id="registry-title"><strong id="total">—</strong> 个配置资源</p><button class="icon-button" id="refresh" type="button">↻ 刷新</button></div>
      <div class="cards" id="results" aria-live="polite" aria-busy="true"><div class="loading">正在读取 Preset 资源…</div></div>
    </section>
  </div>
</main>

<dialog id="editor">
  <form class="editor" id="preset-form">
    <div class="editor-head"><div><p class="eyebrow" id="editor-mode">Create resource</p><h2 id="editor-title">新建 Preset</h2></div><button class="close" id="close" type="button" aria-label="关闭">×</button></div>
    <div class="editor-body">
      <div class="form-error" id="form-error" role="alert"></div>
      <input id="preset-id" type="hidden">
      <fieldset><legend>资源身份</legend><div class="form-grid">
        <div class="field"><label for="name">名称</label><input id="name" required maxlength="128" pattern="[a-z0-9](?:[a-z0-9-]{0,126}[a-z0-9])?" placeholder="owner-repo-review"><p class="hint">小写字母、数字和连字符；用于稳定识别配置。</p></div>
        <div class="field"><span class="field-label">资源状态</span><label class="check-row"><input id="enabled" type="checkbox" checked>启用并参与运行时匹配</label></div>
        <div class="field wide"><label for="description">说明</label><input id="description" maxlength="2000" placeholder="说明这份配置服务的仓库或审查策略"></div>
      </div></fieldset>

      <fieldset><legend>匹配条件</legend><div class="form-grid">
        <div class="field"><label for="task-kind">任务类型</label><select id="task-kind" required><option value="review">Review</option><option value="agent_task">AgentTask</option></select></div>
        <div class="field"><label for="scope">作用域</label><select id="scope" required><option value="global">Global</option><option value="repository">Repository</option></select></div>
        <div class="form-grid wide repository-fields" id="repository-fields" hidden>
          <div class="field"><label for="provider">代码平台</label><select id="provider"><option value="github">GitHub</option><option value="gitlab">GitLab</option></select></div>
          <div class="field"><label for="repo-full-name">仓库</label><input id="repo-full-name" maxlength="512" placeholder="owner/repository"></div>
        </div>
      </div></fieldset>

      <fieldset><legend>Agent 组合</legend><div class="form-grid">
        <div class="field"><label for="agent-id">Agent ID</label><input id="agent-id" required maxlength="128" pattern="[a-z0-9](?:[a-z0-9-]{0,126}[a-z0-9])?" value="code-review"></div>
        <div class="field"><label for="task-type">Task Type</label><input id="task-type" required maxlength="128" pattern="[a-z0-9](?:[a-z0-9-]{0,126}[a-z0-9])?" value="code-review"></div>
        <div class="field wide"><label for="skills">Repository Skills</label><textarea id="skills" placeholder="code-review&#10;security-analysis"></textarea><p class="hint">每行一个；第一项是 Primary，其余项是 Supporting。留空使用 Agent 默认 Skill。</p></div>
      </div></fieldset>

      <fieldset><legend>模型覆盖（可选）</legend><div class="form-grid">
        <div class="field"><label for="model-provider">Provider</label><input id="model-provider" maxlength="64" placeholder="留空继承 Runtime"></div>
        <div class="field"><label for="model-id">Model ID</label><input id="model-id" maxlength="128" placeholder="留空继承 Runtime"></div>
        <div class="field"><label for="thinking-level">Thinking Level</label><select id="thinking-level"><option value="">继承 Runtime</option><option>minimal</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option></select></div>
      </div></fieldset>

      <fieldset><legend>能力与预算</legend><div class="form-grid">
        <div class="field wide"><label class="check-row"><input id="override-tools" type="checkbox">覆盖 Agent Tool 列表</label><p class="hint">只能选择已安装 Agent allow-list 的子集；不勾选表示继承。</p></div>
        <div class="field wide tool-fields" id="tool-fields" hidden><label for="tools">Tools</label><textarea id="tools" placeholder="repository.list-files&#10;repository.read-file&#10;repository.git-diff"></textarea><p class="hint">每行一个。勾选后留空表示只保留结果提交 Tool。</p></div>
        <div class="field"><label for="max-turns">最大回合数</label><input id="max-turns" type="number" min="1" max="1000" step="1" placeholder="继承 Agent"></div>
        <div class="field"><label for="max-tool-calls">最大 Tool 调用</label><input id="max-tool-calls" type="number" min="1" max="10000" step="1" placeholder="继承 Agent"></div>
        <div class="field"><label for="max-result-bytes">最大结果字节</label><input id="max-result-bytes" type="number" min="1" max="10000000" step="1" placeholder="继承 Agent"></div>
      </div></fieldset>

      <details class="json-preview" id="json-details" hidden><summary>查看当前结构化资源</summary><pre id="json-output"></pre></details>
    </div>
    <div class="editor-foot"><button class="danger" id="delete" type="button" hidden>删除资源</button><div><button class="quiet" id="cancel" type="button">取消</button><button class="primary" id="save" type="submit">保存配置</button></div></div>
  </form>
</dialog>
<div class="toast" id="toast" role="status"></div><div class="visually-hidden" id="announcer" aria-live="assertive"></div>

<script>
const API='/api/v1/agent-presets';
const PROXY_TOKEN=new URLSearchParams(location.search).get('token')||'';
const state={items:[],loading:false};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const lines=value=>String(value||'').split(/\r?\n|,/).map(item=>item.trim()).filter(Boolean);
const displayKind=value=>value==='agent_task'?'AgentTask':'Review';
const displayScope=item=>item.scope==='repository'?(item.repo_full_name||'Repository'):'全局默认';
function requestHeaders(withBody=false){const headers={Accept:'application/json'};if(withBody)headers['Content-Type']='application/json';if(PROXY_TOKEN)headers['X-Review-Token']=PROXY_TOKEN;return headers}
function detailMessage(body,status){const detail=body?.detail;if(typeof detail==='string')return detail;if(Array.isArray(detail))return detail.map(item=>item.msg||String(item)).join('；');if(status===401||status===403)return '当前凭据无权管理 Preset，请通过受保护的 operator 入口访问。';if(status===409)return '同一任务和作用域已经存在 Preset，请编辑现有资源。';return `Preset 服务返回错误（${status}）`}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...requestHeaders(Boolean(options.body)),...(options.headers||{})}});if(response.status===204)return null;let body=null;try{body=await response.json()}catch{}if(!response.ok)throw new Error(detailMessage(body,response.status));return body}
function query(){const params=new URLSearchParams({limit:'200',offset:'0'});const fields={task_kind:$('#filter-kind').value,scope:$('#filter-scope').value,provider:$('#filter-provider').value,repo_full_name:$('#filter-repository').value.trim(),enabled:$('#filter-enabled').value};for(const [key,value] of Object.entries(fields))if(value)params.set(key,value);return params}
function renderLimits(item){const values=[];if(item.limits?.max_turns)values.push(`<span class="limit">turns <b>${esc(item.limits.max_turns)}</b></span>`);if(item.limits?.max_tool_calls)values.push(`<span class="limit">tools <b>${esc(item.limits.max_tool_calls)}</b></span>`);if(item.limits?.max_result_bytes)values.push(`<span class="limit">result <b>${esc(item.limits.max_result_bytes)}</b></span>`);if(!values.length)values.push('<span class="limit">预算 <b>继承 Agent</b></span>');values.push(`<span class="limit">Tool <b>${item.tools===null?'继承':item.tools.length+' 项'}</b></span>`);return values.join('')}
function renderSkills(item){const skills=Array.isArray(item.repository_skills)?item.repository_skills:[];if(!skills.length)return '<span class="skill">Agent 默认 Skill</span>';return skills.map((skill,index)=>`<span class="skill ${index?'support':''}">${index?'＋':'P'} · ${esc(skill)}</span>`).join('')}
function renderCard(item){const model=item.model?.id||item.model?.provider||'Runtime 默认';return `<article class="preset-card ${item.enabled?'':'disabled'}"><div><div class="preset-title"><h2 title="${esc(item.name)}">${esc(item.name)}</h2><span class="revision">r${esc(item.revision)}</span></div><p class="description">${esc(item.description||'未填写说明')}</p><div class="badges"><span class="badge ${esc(item.scope)}">${item.scope==='global'?'GLOBAL':'REPOSITORY'}</span><span class="badge ${esc(item.task_kind)}">${esc(displayKind(item.task_kind))}</span><span class="badge ${item.enabled?'enabled':'off'}">${item.enabled?'ENABLED':'DISABLED'}</span></div></div><div><div class="mini-route"><div class="mini-node"><small>Scope</small><strong title="${esc(displayScope(item))}">${esc(displayScope(item))}</strong></div><div class="arrow"></div><div class="mini-node"><small>Agent / Task</small><strong title="${esc(item.agent_id)} / ${esc(item.task_type)}">${esc(item.agent_id)} / ${esc(item.task_type)}</strong></div><div class="arrow"></div><div class="mini-node"><small>Model</small><strong title="${esc(model)}">${esc(model)}</strong></div></div><div class="skills">${renderSkills(item)}</div><div class="limits">${renderLimits(item)}</div></div><div class="card-actions"><button class="quiet" type="button" data-action="edit" data-id="${esc(item.id)}">查看 / 编辑</button><button class="icon-button" type="button" data-action="toggle" data-id="${esc(item.id)}">${item.enabled?'停用':'启用'}</button></div></article>`}
function render(){if(!state.items.length){$('#results').innerHTML='<div class="empty"><div><strong>没有匹配的 Preset</strong><p>调整筛选条件，或新建一份 Global / Repository 配置来建立执行路由。</p></div></div>';return}$('#results').innerHTML=state.items.map(renderCard).join('')}
async function load(){if(state.loading)return;state.loading=true;$('#refresh').disabled=true;$('#results').setAttribute('aria-busy','true');$('#results').innerHTML='<div class="loading">正在读取 Preset 资源…</div>';try{const data=await api(`${API}?${query()}`);state.items=Array.isArray(data.items)?data.items:[];$('#total').textContent=String(data.total??state.items.length);render()}catch(error){$('#results').innerHTML=`<div class="load-error"><div><strong>配置加载失败</strong><p>${esc(error.message)}</p></div></div>`;$('#total').textContent='—'}finally{state.loading=false;$('#refresh').disabled=false;$('#results').setAttribute('aria-busy','false')}}
function syncScope(){const repository=$('#scope').value==='repository';$('#repository-fields').hidden=!repository;$('#provider').required=repository;$('#repo-full-name').required=repository}
function syncTools(){const override=$('#override-tools').checked;$('#tool-fields').hidden=!override;$('#tools').disabled=!override}
function setValue(selector,value=''){$(selector).value=value??''}
function defaultCombination(){const agent=$('#task-kind').value==='agent_task'?'pr-assistant':'code-review';setValue('#agent-id',agent);setValue('#task-type',$('#task-kind').value==='agent_task'?'message-command':'code-review');setValue('#skills',agent)}
function openEditor(item=null){$('#preset-form').reset();$('#form-error').classList.remove('show');$('#preset-id').value=item?.id||'';$('#editor-mode').textContent=item?'Edit resource':'Create resource';$('#editor-title').textContent=item?'编辑 Preset':'新建 Preset';$('#delete').hidden=!item;$('#json-details').hidden=!item;if(item){setValue('#name',item.name);setValue('#description',item.description);$('#enabled').checked=Boolean(item.enabled);setValue('#task-kind',item.task_kind);setValue('#scope',item.scope);setValue('#provider',item.provider||'github');setValue('#repo-full-name',item.repo_full_name);setValue('#agent-id',item.agent_id);setValue('#task-type',item.task_type);setValue('#skills',(item.repository_skills||[]).join('\n'));setValue('#model-provider',item.model?.provider);setValue('#model-id',item.model?.id);setValue('#thinking-level',item.model?.thinking_level);$('#override-tools').checked=item.tools!==null;setValue('#tools',(item.tools||[]).join('\n'));setValue('#max-turns',item.limits?.max_turns);setValue('#max-tool-calls',item.limits?.max_tool_calls);setValue('#max-result-bytes',item.limits?.max_result_bytes);$('#json-output').textContent=JSON.stringify(item,null,2)}else{$('#enabled').checked=true;setValue('#task-kind','review');setValue('#scope','global');setValue('#provider','github');defaultCombination()}syncScope();syncTools();$('#editor').showModal();setTimeout(()=>$('#name').focus(),0)}
function numberOrNull(selector){const value=$(selector).value;return value?Number(value):null}
function payload(){const model={provider:$('#model-provider').value.trim()||null,id:$('#model-id').value.trim()||null,thinking_level:$('#thinking-level').value||null};const limits={max_turns:numberOrNull('#max-turns'),max_tool_calls:numberOrNull('#max-tool-calls'),max_result_bytes:numberOrNull('#max-result-bytes')};const repository=$('#scope').value==='repository';return {name:$('#name').value.trim(),description:$('#description').value.trim()||null,task_kind:$('#task-kind').value,scope:$('#scope').value,provider:repository?$('#provider').value:null,repo_full_name:repository?$('#repo-full-name').value.trim():null,agent_id:$('#agent-id').value.trim(),task_type:$('#task-type').value.trim(),repository_skills:lines($('#skills').value),model:Object.values(model).some(Boolean)?Object.fromEntries(Object.entries(model).filter(([,value])=>value!==null)):null,tools:$('#override-tools').checked?lines($('#tools').value):null,limits:Object.values(limits).some(value=>value!==null)?Object.fromEntries(Object.entries(limits).filter(([,value])=>value!==null)):null,enabled:$('#enabled').checked}}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove('show'),2600)}
async function save(event){event.preventDefault();const form=$('#preset-form');if(!form.reportValidity())return;const id=$('#preset-id').value;$('#save').disabled=true;$('#form-error').classList.remove('show');try{await api(id?`${API}/${encodeURIComponent(id)}`:API,{method:id?'PATCH':'POST',body:JSON.stringify(payload())});$('#editor').close();toast(id?'配置已保存':'Preset 已创建');$('#announcer').textContent=id?'Preset 配置已保存':'Preset 已创建';await load()}catch(error){$('#form-error').textContent=error.message;$('#form-error').classList.add('show');$('#form-error').scrollIntoView({block:'nearest'})}finally{$('#save').disabled=false}}
async function toggle(item){try{await api(`${API}/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({enabled:!item.enabled})});toast(item.enabled?'Preset 已停用':'Preset 已启用');await load()}catch(error){toast(error.message)}}
async function remove(){const id=$('#preset-id').value;const item=state.items.find(value=>value.id===id);if(!id||!item)return;if(!confirm(`删除 Preset “${item.name}”？\n删除后，该作用域会回退到下一层配置。`))return;$('#delete').disabled=true;try{await api(`${API}/${encodeURIComponent(id)}`,{method:'DELETE'});$('#editor').close();toast('Preset 已删除');await load()}catch(error){$('#form-error').textContent=error.message;$('#form-error').classList.add('show')}finally{$('#delete').disabled=false}}
if(PROXY_TOKEN)document.querySelectorAll('[data-token-link]').forEach(link=>{const url=new URL(link.href,location.origin);url.searchParams.set('token',PROXY_TOKEN);link.href=url.href});$('#filters').addEventListener('submit',event=>{event.preventDefault();load()});$('#reset').addEventListener('click',()=>{$('#filters').reset();load()});$('#refresh').addEventListener('click',load);$('#create').addEventListener('click',()=>openEditor());$('#close').addEventListener('click',()=>$('#editor').close());$('#cancel').addEventListener('click',()=>$('#editor').close());$('#scope').addEventListener('change',syncScope);$('#override-tools').addEventListener('change',syncTools);$('#task-kind').addEventListener('change',defaultCombination);$('#preset-form').addEventListener('submit',save);$('#delete').addEventListener('click',remove);$('#results').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const item=state.items.find(value=>value.id===button.dataset.id);if(!item)return;button.dataset.action==='edit'?openEditor(item):toggle(item)});$('#editor').addEventListener('click',event=>{if(event.target===$('#editor'))$('#editor').close()});load();
</script>
</body>
</html>"""
